#!/usr/bin/env ruby
# encoding: UTF-8
system "clear"
def banner()
red = "\033[01;31m"
green = "\033[01;32m"
yellow = "\033[01;33m"
white = "\033[01;37m"
blue = "\033[00;34m"
puts "\n"
puts "#{green}        ███╗   ██╗ ██████╗  ██████╗ ██████╗      ██████╗ ███████╗"
puts "#{yellow}        ████╗  ██║██╔═══██╗██╔═══██╗██╔══██╗    ██╔═══██╗██╔════╝"
puts "#{blue}        ██╔██╗ ██║██║   ██║██║   ██║██████╔╝    ██║   ██║███████╗"
puts "#{white}        ██║╚██╗██║██║   ██║██║   ██║██╔══██╗    ██║   ██║╚════██║"
puts "#{red}        ██║ ╚████║╚██████╔╝╚██████╔╝██████╔╝    ╚██████╔╝███████║"
puts "#{yellow}        ╚═╝  ╚═══╝ ╚═════╝  ╚═════╝ ╚═════╝      ╚═════╝ ╚══════╝"                                             
puts "\n"
puts "#{blue}        ------------------- Chankruze's Own OS -------------------"
puts "\n"
puts "#{yellow}"
puts "\n"
end
green = "\033[01;32m"
yellow = "\033[01;33m"
blue = "\033[00;34m"
banner()
puts "        ************* Fetching Source Codes *************"
puts "\n"
puts "#{blue}Fetching Kernel .......#{yellow}"
puts "\n"
system "git clone https://github.com/NoobOS/kernel.git"
puts "\n"
puts "#{blue}Fetching Files .......#{yellow}"
puts "\n"
system "git clone https://github.com/NoobOS/src.git"
puts "\n"
puts "#{blue}Fetching Libs .......#{yellow}"
puts "\n"
system "git clone https://github.com/NoobOS/include.git"
puts "\n"
puts "\n"
puts "#{blue}Fetching Libs .......#{yellow}"
puts "\n"
system "clear"
banner()
green = "\033[01;32m"
puts "#{yellow}        ************* Fetching Dependencies *************#{green}"
puts "\n"
system "sudo apt install g++ binutils libc6-dev-i386 xorriso grub-coreboot virtualbox virtualbox-qt"
puts "\n"
puts "#{blue}        ************* Setup Finished *************"